### ISSUE TITLE
Target tensor is not cast to 'dtype=long'

### ISSUE THREAD

**Issue by StuckinPhD** [wolny/pytorch-3dunet#28]
In the file transforms.py and in ToTensor() the line below is supposed to convert the tensor to the specified data type:

`return torch.from_numpy(m.astype(dtype=self.dtype))`

But even if ``long`` is given as the dtype in the .yaml file, it is returned as ``int32``. This is not a problem for ``DiceLoss()`` but fails to work when using ``CrossEntropyLoss()`` as we get the error:

````
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/s/PycharmProjects/d/train.py", line 122, in <module>
    main()
  File "C:/Users/s/PycharmProjects/d/train.py", line 118, in main
    trainer.fit()
  File "C:\Users\s\PycharmProjects\d\unet3d\trainer.py", line 134, in fit
    should_terminate = self.train(self.loaders['train'])
  File "C:\Users\s\PycharmProjects\d\unet3d\trainer.py", line 162, in train
    output, loss = self._forward_pass(input, target, weight)
  File "C:\Users\s\PycharmProjects\d\unet3d\trainer.py", line 266, in _forward_pass
    loss = self.loss_criterion(output, target)
  File "C:\Users\s\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\s\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\loss.py", line 904, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "C:\Users\s\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\functional.py", line 1970, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "C:\Users\s\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\functional.py", line 1806, in nll_loss
    input, target, weight, reduction_enum, ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target'
````

i tried changing this in torch after numpy conversion:

`m_ = torch.from_numpy(m)   
        return eval('m_.'+self.dtype+'()')`

which works as far as casting to int64 goes but immediately after I get cuda memory errors.

**Comment by StuckinPhD** [comment]
Also, I'll add an additional question to my above request.

How come ``slice_builder`` is used in ``train_config_dice.yaml``:

```
loaders:
  slice_builder: 'FilterSliceBuilder'
  # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
  train_patch: [32, 64, 64]
  # train stride between patches
  train_stride: [8, 16, 16]
```

and not used in ``train_config_ce.yaml``:

```
loaders:
  # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
  train_patch: [32, 64, 64]
  # train stride between patches
  train_stride: [8, 16, 16]
```

while for the same dataset and each epoch is 6 iterations for ``dice_config`` while 200 iterations for ``ce_config``

Thanks

**Comment by wolny** [comment]
Hi @StuckinPhD,

if you're training with CrossEntropy then `dtype: long` must be present in the transformer (see: https://github.com/wolny/pytorch-3dunet/blob/master/resources/train_config_ce.yaml#L109) cause that's what Pytorch's CrossEntropy loss expects. I have no idea why `ToTensor` would return `int32` instead of `long` in this case, however I see that you're using Windows and I've never tested my code on Windows, so to be on the safe side make sure to use Linux OS, e.g. Ubuntu. 

Regarding the `slice_builder` I think `FilterSliceBuilder` is just a leftover in my config. It does make sense to use it if you have a lot of regions that you want to ignore in your training dataset in order to speed up training (otherwise the network will be going over patches of mostly background label, see: https://github.com/wolny/pytorch-3dunet/blob/master/datasets/hdf5.py#L85 for more details). I'll remove it from the config not to cause confusion.

**Comment by victoryc** [comment]
Hi @StuckinPhD, did you find a solution for this on Windows?

Thanks.

**Comment by victoryc** [comment]
For the benefit of anyone else running into this issue on Windows: I was able to solve this by setting the dtype for the label to be 'int64' instead of 'long' in the config file.
