### ISSUE TITLE
Error when using GeneralizedDiceLoss and  with custom data

### ISSUE THREAD

**Issue by zzz123xyz** [wolny/pytorch-3dunet#36]
Hi wolny
    I have followed the instruction in your readme and create a 4D label HDF5 data (CxDxHxW). Each channel has binary mask, as I want to segment my data into 5 classes. I check my data and label in HDFview, the data is with 3 dimensions 150 x 256 x 256 and the label is with 4 dimensions 5 x 150 x 256 x 256. I run into the following error. I don't know what is the correct way to 

`Traceback (most recent call last):
  File "train.py", line 123, in <module>
    main()
  File "train.py", line 119, in main
    trainer.fit()
  File "/home/user1/working_dir/MRI_segmentation/pytorch-3dunet/unet3d/trainer.py", line 134, in fit
    should_terminate = self.train(self.loaders['train'])
  File "/home/user1/working_dir/MRI_segmentation/pytorch-3dunet/unet3d/trainer.py", line 156, in train
    for i, t in enumerate(train_loader):
  File "/home/user1/anaconda2/envs/3dunet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/user1/anaconda2/envs/3dunet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/user1/anaconda2/envs/3dunet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/user1/anaconda2/envs/3dunet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/user1/anaconda2/envs/3dunet/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 85, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/user1/working_dir/MRI_segmentation/pytorch-3dunet/datasets/hdf5.py", line 201, in __getitem__
    self.labels, label_idx, self.label_transform)
  File "/home/user1/working_dir/MRI_segmentation/pytorch-3dunet/datasets/hdf5.py", line 216, in _transform_patches
    transformed_patch = transformer(dataset[label_idx])
  File "/home/user1/anaconda2/envs/3dunet/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
  File "/home/user1/working_dir/MRI_segmentation/pytorch-3dunet/augment/transforms.py", line 139, in __call__
    assert m.ndim == 3
AssertionError`

**Comment by danarteaga** [comment]
Not sure exactly what is going on here, but it appears that your data is not 3D when it is being passed to the ElasticDeformation transformer (for data augmentation)..

**Comment by zzz123xyz** [comment]
> Not sure exactly what is going on here, but it appears that your data is not 3D when it is being passed to the ElasticDeformation transformer (for data augmentation)..

Yeah the problem is caused by the ElasticDeformation transformer. my data is with 3 dimensions 150 x 256 x 256 and the label is with 4 dimensions 5 x 150 x 256 x 256, but it looks like the ElasticDeformation transformer can only accept 3D data, not the 4D (with channel dimension as the 4th dim). I don't know how to correctly use the ElasticDeformation transformer, so I just comment on it. I hope the author can solve this problem in a future version!
