### ISSUE TITLE
A problem with validation

### ISSUE THREAD

**Issue by ViiSkor** [wolny/pytorch-3dunet#46]
I ran `train.py` with default ` train_config_dice.yaml ` and got this error while validation.
```
2019-11-03 22:42:58,612 [MainThread] INFO UNet3DTrainer - Training iteration 1. Batch 0. Epoch [0/49]
2019-11-03 22:43:37,006 [MainThread] INFO UNet3DTrainer - Training iteration 2. Batch 1. Epoch [0/49]
2019-11-03 22:43:37,567 [MainThread] INFO UNet3DTrainer - Training iteration 3. Batch 2. Epoch [0/49]
2019-11-03 22:43:38,230 [MainThread] INFO UNet3DTrainer - Training iteration 4. Batch 3. Epoch [0/49]
2019-11-03 22:43:38,887 [MainThread] INFO UNet3DTrainer - Training iteration 5. Batch 4. Epoch [0/49]
2019-11-03 22:43:39,561 [MainThread] INFO UNet3DTrainer - Training iteration 6. Batch 5. Epoch [0/49]
2019-11-03 22:43:40,237 [MainThread] INFO UNet3DTrainer - Training iteration 7. Batch 6. Epoch [0/49]
2019-11-03 22:43:40,880 [MainThread] INFO UNet3DTrainer - Training iteration 8. Batch 7. Epoch [0/49]
2019-11-03 22:43:41,539 [MainThread] INFO UNet3DTrainer - Training iteration 9. Batch 8. Epoch [0/49]
2019-11-03 22:43:42,198 [MainThread] INFO UNet3DTrainer - Training iteration 10. Batch 9. Epoch [0/49]
2019-11-03 22:43:42,858 [MainThread] INFO UNet3DTrainer - Training iteration 11. Batch 10. Epoch [0/49]
2019-11-03 22:43:43,528 [MainThread] INFO UNet3DTrainer - Training iteration 12. Batch 11. Epoch [0/49]
2019-11-03 22:43:44,192 [MainThread] INFO UNet3DTrainer - Training iteration 13. Batch 12. Epoch [0/49]
2019-11-03 22:43:44,863 [MainThread] INFO UNet3DTrainer - Training iteration 14. Batch 13. Epoch [0/49]
2019-11-03 22:43:45,516 [MainThread] INFO UNet3DTrainer - Training iteration 15. Batch 14. Epoch [0/49]
2019-11-03 22:43:46,179 [MainThread] INFO UNet3DTrainer - Training iteration 16. Batch 15. Epoch [0/49]
2019-11-03 22:43:46,845 [MainThread] INFO UNet3DTrainer - Training iteration 17. Batch 16. Epoch [0/49]
2019-11-03 22:43:47,509 [MainThread] INFO UNet3DTrainer - Training iteration 18. Batch 17. Epoch [0/49]
2019-11-03 22:43:48,247 [MainThread] INFO UNet3DTrainer - Training iteration 19. Batch 18. Epoch [0/49]
2019-11-03 22:43:49,043 [MainThread] INFO UNet3DTrainer - Training iteration 20. Batch 19. Epoch [0/49]
2019-11-03 22:43:49,803 [MainThread] INFO UNet3DTrainer - Validating...
2019-11-03 22:44:32,827 [MainThread] INFO UNet3DTrainer - Validation iteration 0
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    main()
  File "train.py", line 124, in main
    trainer.fit()
  File "C:\Users\vikto\Desktop\pytorch-3dunet\unet3d\trainer.py", line 146, in fit
    should_terminate = self.train(self.loaders['train'])
  File "C:\Users\vikto\Desktop\pytorch-3dunet\unet3d\trainer.py", line 185, in train
    eval_score = self.validate(self.loaders['val'])
  File "C:\Users\vikto\Desktop\pytorch-3dunet\unet3d\trainer.py", line 246, in validate
    eval_score = self.eval_criterion(output, target)
  File "C:\Users\vikto\Desktop\pytorch-3dunet\unet3d\metrics.py", line 88, in __call__
    per_channel_iou.append(self._jaccard_index(binary_prediction[c], _target[c]))
  File "C:\Users\vikto\Desktop\pytorch-3dunet\unet3d\metrics.py", line 113, in _jaccard_index
    return np.nan_to_num(torch.sum(prediction & target).float() / torch.sum(prediction | target).float())
  File "<__array_function__ internals>", line 6, in nan_to_num
  File "C:\Users\vikto\AppData\Local\Continuum\anaconda3\envs\3dunet\lib\site-packages\numpy\lib\type_check.py", line 456, in nan_to_num
    x = _nx.array(x, subok=True, copy=copy)
  File "C:\Users\vikto\AppData\Local\Continuum\anaconda3\envs\3dunet\lib\site-packages\torch\tensor.py", line 433, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```
I have the same error when running it on my laptop and google colab.

**Comment by wolny** [comment]
Indeed that's a mistake I've done in my recent commit. It's been fixed in my latest commit 1f5c909aba26f1728461afdb31e110bdba08c11a.

**Comment by ViiSkor** [comment]
@wolny , thank you for your awesome work!

**Comment by wolny** [comment]
Hi @ViiSkor,

thanks! I hope you will find the code useful. Cheers for reporting the issue.
