### ISSUE TITLE
Run your demo

### ISSUE THREAD

**Issue by ZhangMingHui123** [wolny/pytorch-3dunet#48]
I want to run your demo，however encount this issue could you please tell me why? thanks!!!
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    main()
  File "train.py", line 124, in main
    trainer.fit()
  File "E:\Studyfile_ZMH\GraduationProject\code\pytorch-3dunet-master\unet3d\trainer.py", line 146, in fit
    should_terminate = self.train(self.loaders['train'])
  File "E:\Studyfile_ZMH\GraduationProject\code\pytorch-3dunet-master\unet3d\trainer.py", line 174, in train
    output, loss = self._forward_pass(input, target, weight)
  File "E:\Studyfile_ZMH\GraduationProject\code\pytorch-3dunet-master\unet3d\trainer.py", line 279, in _forward_pass
    loss = self.loss_criterion(output, target)
  File "D:\Anacondasetup\envs\py3.6\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anacondasetup\envs\py3.6\lib\site-packages\torch\nn\modules\loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "D:\Anacondasetup\envs\py3.6\lib\site-packages\torch\nn\functional.py", line 2009, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "D:\Anacondasetup\envs\py3.6\lib\site-packages\torch\nn\functional.py", line 1854, in nll_loss
    input, target, weight, reduction_enum, ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss2d_forward

**Comment by wolny** [comment]
Hi @ZhangMingHui123,

looks like you're using Windows. Linux OS is a requirement to run this project
